import { authenticatedFetch } from "./vendor/auth-runtime.js";
const SUBJECTS=["國文","英文","數學","自然","社會"];
const FILES={國文:"chinese",英文:"english",數學:"math",自然:"science",社會:"social"};
const STORAGE_KEY="capQuizV2",DAILY_GOAL=20,LESSON_SIZE=10;let syncTimer,audioContext,bgmAudio,musicStarted=false,effectsMaster;
const SPECIES=[
{id:"ember",name:"焰芽",subject:"國文",icon:"🔥",gift:"文字記憶",color:"coral"},
{id:"sky",name:"晴葉",subject:"英文",icon:"💠",gift:"語感飛行",color:"blue"},
{id:"gold",name:"金晶",subject:"數學",icon:"💎",gift:"計算靈光",color:"gold"},
{id:"moss",name:"苔森",subject:"自然",icon:"🌿",gift:"觀察之眼",color:"green"},
{id:"way",name:"尋路",subject:"社會",icon:"🧭",gift:"地圖直覺",color:"violet"}
];
const RELICS=["露珠背包","學者單眼鏡","葉片斗篷","太陽徽章","晶芽王冠","木紋圓盾","螢光提燈","風翼靴","花瓣圍巾","星圖卷軸","幸運澆水壺","古芽羅盤"];
const RELIC_EFFECTS={"露珠背包":"答對額外 +2 露珠","學者單眼鏡":"答題 XP +10%","葉片斗篷":"探索時間 -15%","太陽徽章":"答對額外 +2 陽光","晶芽王冠":"每 8 題可獲得種子","木紋圓盾":"挑戰增加 1 顆愛心","螢光提燈":"探索獎勵 +20%","風翼靴":"探索時間 -25%","花瓣圍巾":"連擊 XP 額外 +2","星圖卷軸":"答題 XP +15%","幸運澆水壺":"培育少花 5 露珠","古芽羅盤":"探索獎勵 +25%"};
const BUILDINGS=[{id:"greenhouse",name:"種子溫室",icon:"🏡",cost:100,effect:"種子改為每 8 題獲得"},{id:"pond",name:"露珠池",icon:"💧",cost:180,effect:"答對額外 +1 露珠"},{id:"treehouse",name:"探索樹屋",icon:"🌳",cost:300,effect:"探索獎勵 +50%"},{id:"gate",name:"星光遺跡門",icon:"🏛️",cost:500,effect:"所有答題 XP +20%"}];
const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")||{};
const initialWorld={sunshine:0,dew:0,seeds:0,buildings:[],spirits:{ember:1,sky:0,gold:0,moss:0,way:0},team:[],relics:[],equipment:{},expedition:null};
const defaultProfile={name:"",avatar:"遠",spirit:"moss",theme:"ruins",accent:"cyan",dailyGoal:20,sound:true,music:true,volume:.55,motion:true,haptic:true,configured:false};
const state={profile:{...defaultProfile,...saved.profile},subject:saved.subject||"數學",difficulty:saved.difficulty||"",unit:saved.unit||"",history:saved.history||[],wrongs:saved.wrongs||[],review:saved.review||{},game:{xp:0,...saved.game},world:{...initialWorld,...saved.world,spirits:{...initialWorld.spirits,...saved.world?.spirits},equipment:{...initialWorld.equipment,...saved.world?.equipment}},wrongMode:false,questions:[],current:null,selected:null,answered:false,questionBag:[],recent:saved.recent||[],view:"quiz",lesson:{active:false,answered:0,correct:0,xp:0,combo:0,hearts:5,shouldEnd:false,seen:[]}};
const ids=["exploreMiles","missionTrack","subjectTabs","difficultyFilter","unitFilter","resetFilters","loading","quiz","empty","meta","question","options","feedback","wrongButton","mainButton","doneCount","accuracy","wrongCount","todayCount","streakDays","xpCount","heartCount","questMessage","goalRing","goalCount","startChallenge","lessonProgress","lessonCount","exitChallenge","progressBar","lessonHearts","rewardPop","resultModal","resultTitle","resultSummary","resultXp","resultAccuracy","closeResult","sunshineCount","dewCount","seedCount","cultivateSeed","hatchSeed","hatchHint","gardenBuildings","spiritTotal","spiritGrid","relicList","teamCount","teamSlots","expeditionStatus","battleStage","battleSpirit","enemyShield","comboBadge","impactLayer","explorerAvatar","heroSpirit","profileModal","profileName","profileAvatar","profileSpirit","profileTheme","profileGoal","profileAccent","soundEnabled","motionEnabled","hapticEnabled","profileAvatarPreview","profileNamePreview","profileSpiritPreview","soundToggle","musicToggle","effectsToggle","volumeControl","audioStatus","officialExamList"];
const elements=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
function secureRandomIndex(max){if(max<=1)return 0;const limit=0x100000000-(0x100000000%max),buffer=new Uint32Array(1);do{crypto.getRandomValues(buffer)}while(buffer[0]>=limit);return buffer[0]%max}
function shuffle(list){const result=[...list];for(let index=result.length-1;index>0;index--){const swapIndex=secureRandomIndex(index+1);[result[index],result[swapIndex]]=[result[swapIndex],result[index]]}return result}
function uniqueQuestionPool(pool){const ids=new Set(),stems=new Set();return pool.filter(item=>{const stem=item.question.replace(/\s+/g,"").toLowerCase();if(ids.has(item.id)||stems.has(stem))return false;ids.add(item.id);stems.add(stem);return true})}
function diverseQuestionQueue(pool,count=Infinity){const groups=new Map();shuffle(pool).forEach(item=>{const key=`${item.unit}|${item.knowledgePoint}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(item)});const queues=shuffle([...groups.values()]),result=[];while(queues.some(group=>group.length)&&result.length<count){for(const group of queues){if(group.length&&result.length<count)result.push(group.shift())}}return result}
function buildChallengeQueue(){const pool=uniqueQuestionPool(filteredPool()).filter(item=>item.id!==state.current?.id),recentIds=new Set(state.recent.slice(-100)),fresh=pool.filter(item=>!recentIds.has(item.id));const distinctPoints=new Set(pool.map(item=>`${item.unit}|${item.knowledgePoint}`));if(pool.length<LESSON_SIZE||distinctPoints.size<LESSON_SIZE)return [];const selected=diverseQuestionQueue(fresh,LESSON_SIZE);if(selected.length<LESSON_SIZE){const selectedIds=new Set(selected.map(item=>item.id));selected.push(...diverseQuestionQueue(pool.filter(item=>!selectedIds.has(item.id)),LESSON_SIZE-selected.length))}return selected}
function snapshot(){return {profile:state.profile,subject:state.subject,difficulty:state.difficulty,unit:state.unit,history:state.history,wrongs:state.wrongs,review:state.review,game:state.game,world:state.world,recent:state.recent,migratedV1:true}} function save(){const data=snapshot();localStorage.setItem(STORAGE_KEY,JSON.stringify(data));clearTimeout(syncTimer);syncTimer=setTimeout(()=>authenticatedFetch("/api/progress",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({state:data})}).catch(()=>{}),800)}
function migrateV1(){if(saved.migratedV1||state.history.length)return;const oldHistory=JSON.parse(localStorage.getItem("hist")||"[]"),oldWrongs=JSON.parse(localStorage.getItem("wrongs")||"[]");if(oldHistory.length||oldWrongs.length){state.history=oldHistory.map(item=>({...item,subject:item.s||item.subject}));state.wrongs=oldWrongs;save()}}
function localDateKey(timestamp=Date.now()){const date=new Date(Number(timestamp)||timestamp);return Number.isNaN(date.getTime())?"":`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function todayHistory(){const today=localDateKey();return state.history.filter(item=>localDateKey(item.timestamp??item.ts)===today)}
function streakDays(){const active=new Set(state.history.map(item=>localDateKey(item.timestamp??item.ts)).filter(Boolean));let cursor=new Date();if(!active.has(localDateKey(cursor)))cursor.setDate(cursor.getDate()-1);let streak=0;while(active.has(localDateKey(cursor))){streak++;cursor.setDate(cursor.getDate()-1)}return streak}
async function loadSubject(){elements.loading.classList.remove("hidden");elements.loading.textContent="正在載入題庫…";elements.quiz.classList.add("hidden");elements.empty.classList.add("hidden");try{const response=await fetch(`./data/${FILES[state.subject]}.json?v=3.2.0`);if(!response.ok)throw new Error(`HTTP ${response.status}`);state.questions=await response.json();state.questionBag=[];renderUnits();nextQuestion()}catch(error){elements.loading.textContent=`題庫載入失敗：${error.message}`}}
function filteredPool(){let pool=state.questions.filter(item=>(!state.difficulty||item.difficulty===state.difficulty)&&(!state.unit||item.unit===state.unit));if(state.wrongMode){const ids=new Set(state.wrongs);pool=pool.filter(item=>ids.has(item.id))}return pool}
function refillQuestionBag(){const excluded=new Set(state.lesson.active?state.lesson.seen:state.recent.slice(-100));let pool=filteredPool().filter(item=>!excluded.has(item.id)&&item.id!==state.current?.id);if(pool.length<10)pool=filteredPool().filter(item=>item.id!==state.current?.id);state.questionBag=diverseQuestionQueue(pool)}
function nextQuestion(){if(!state.questionBag.length&&!state.lesson.active)refillQuestionBag();elements.loading.classList.add("hidden");if(!state.questionBag.length){state.current=null;elements.quiz.classList.add("hidden");elements.empty.classList.remove("hidden");updateStats();return}state.current=state.questionBag.shift();state.selected=null;state.answered=false;if(state.lesson.active)state.lesson.seen.push(state.current.id);state.recent.push(state.current.id);state.recent=state.recent.slice(-100);elements.empty.classList.add("hidden");elements.quiz.classList.remove("hidden");renderQuestion()}
function resetBagAndNext(){state.questionBag=[];nextQuestion()}
function renderTabs(){elements.subjectTabs.innerHTML=SUBJECTS.map(subject=>`<button class="tab ${subject===state.subject?"active":""}" data-subject="${subject}" type="button">${subject}</button>`).join("");elements.subjectTabs.querySelectorAll("button").forEach(button=>button.addEventListener("click",async()=>{state.subject=button.dataset.subject;state.unit="";state.wrongMode=false;state.questionBag=[];save();renderTabs();await loadSubject()}))}
function renderUnits(){const units=[...new Set(state.questions.map(item=>item.unit))].sort((a,b)=>a.localeCompare(b,"zh-Hant"));if(state.unit&&!units.includes(state.unit))state.unit="";elements.unitFilter.innerHTML=`<option value="">全部單元</option>${units.map(unit=>`<option value="${unit}">${unit}</option>`).join("")}`;elements.unitFilter.value=state.unit}
function renderQuestion(){const item=state.current;const lessonLabel=state.lesson.active?`第 ${state.lesson.answered+1} / ${LESSON_SIZE} 題｜`:"";elements.meta.textContent=`${lessonLabel}${item.subject}｜${item.gradeSemester}｜${item.unit}｜${item.knowledgePoint}｜${item.difficulty}${state.wrongMode?"｜錯題複習":""}`;elements.question.textContent=item.question;elements.feedback.className="feedback hidden";elements.options.innerHTML=item.options.map((option,index)=>`<button class="option" data-index="${index}" type="button"><b>${String.fromCharCode(65+index)}</b>　${option}</button>`).join("");elements.options.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{if(state.answered)return;state.selected=Number(button.dataset.index);elements.options.querySelectorAll("button").forEach(option=>option.classList.remove("selected"));button.classList.add("selected");playSound("select")}));elements.mainButton.textContent="確認答案";elements.wrongButton.textContent=state.wrongMode?"回一般刷題":"只刷錯題";elements.wrongButton.classList.toggle("hidden",state.lesson.active);updateStats()}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character])}
function renderExplanation(item){
  const steps=(item.solutionSteps?.length?item.solutionSteps:[item.explanation]).map((step,index)=>`<li><span>${index+1}</span><p>${escapeHtml(step)}</p></li>`).join("");
  const related=item.subject==="英文"&&item.relatedWords?.length?`<section class="answer-extra words"><h4>🔤 同義詞／類似詞</h4><p>${item.relatedWords.map(escapeHtml).join("・")}</p></section>`:"";
  return `<div class="solution-guide"><h3>完整解題過程</h3><ol>${steps}</ol>${related}<section class="answer-extra teacher-tip"><h4>💡 老師提醒</h4><p>${escapeHtml(item.teacherTip||"先圈出題目關鍵詞，再逐一檢查選項。")}</p></section></div>`;
}
function showReward(text,correct){elements.rewardPop.textContent=text;elements.rewardPop.style.color=correct?"var(--yellow)":"var(--red)";elements.rewardPop.classList.remove("hidden");elements.rewardPop.getAnimations().forEach(animation=>animation.cancel());requestAnimationFrame(()=>{elements.rewardPop.style.animation="none";requestAnimationFrame(()=>elements.rewardPop.style.animation="reward 1s ease both")});setTimeout(()=>elements.rewardPop.classList.add("hidden"),1000)}
function hasBuilding(id){return (state.world.buildings||[]).includes(id)}
function equippedRelics(){return state.world.team.map(id=>state.world.equipment[id]).filter(Boolean)}
function hasRelic(name){return equippedRelics().includes(name)}
function awardWorld(correct){if(!correct)return;state.world.sunshine+=3+(hasRelic("太陽徽章")?2:0);state.world.dew+=1+(hasBuilding("pond")?1:0)+(hasRelic("露珠背包")?2:0);const seedEvery=hasBuilding("greenhouse")||hasRelic("晶芽王冠")?8:10;if(state.history.length%seedEvery===0){state.world.seeds+=1;showReward("獲得神秘種子！",true)}if(state.history.length%15===0&&state.world.relics.length<RELICS.length){const locked=RELICS.filter(item=>!state.world.relics.includes(item));state.world.relics.push(locked[Math.floor(Math.random()*locked.length)])}}
function checkAnswer(){if(state.answered){if(state.lesson.active&&state.lesson.shouldEnd)return finishChallenge();return nextQuestion()}if(state.selected===null)return alert("請先選一個答案");state.answered=true;const correct=state.selected===state.current.answer;const answeredAt=Date.now();state.history.push({id:state.current.id,subject:state.subject,correct,timestamp:answeredAt});authenticatedFetch("/api/attempts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionId:state.current.id,subject:state.subject,correct,unit:state.current.unit,knowledgePoint:state.current.knowledgePoint,answeredAt})}).catch(()=>{});if(correct)state.wrongs=state.wrongs.filter(id=>id!==state.current.id);else if(!state.wrongs.includes(state.current.id))state.wrongs.push(state.current.id);const previous=state.review[state.current.id]||{intervalDays:0,repetitions:0,easeFactor:2.5};state.review[state.current.id]={...previous,lastReviewedAt:new Date().toISOString(),nextReviewAt:null,repetitions:correct?previous.repetitions+1:0};let earnedXp=correct?10:2;const xpMultiplier=(hasBuilding("gate")?1.2:1)*(hasRelic("學者單眼鏡")?1.1:1)*(hasRelic("星圖卷軸")?1.15:1);earnedXp=Math.round(earnedXp*xpMultiplier);if(state.lesson.active){state.lesson.answered++;if(correct){state.lesson.correct++;state.lesson.combo++;earnedXp+=Math.min(state.lesson.combo-1,5)*2+(hasRelic("花瓣圍巾")?2:0)}else{state.lesson.combo=0;state.lesson.hearts=Math.max(0,state.lesson.hearts-1)}state.lesson.xp+=earnedXp;state.lesson.shouldEnd=state.lesson.answered>=LESSON_SIZE||state.lesson.hearts===0}state.game.xp+=earnedXp;awardWorld(correct);runBattleFeedback(correct,earnedXp);save();elements.options.querySelectorAll("button").forEach((button,index)=>{button.classList.remove("selected");if(index===state.current.answer)button.classList.add("correct");if(index===state.selected&&!correct)button.classList.add("incorrect")});const combo=state.lesson.active&&correct&&state.lesson.combo>=2?`・${state.lesson.combo} 連擊！`:"";elements.feedback.className=`feedback ${correct?"ok":"no"}`;elements.feedback.innerHTML=`<b>${correct?`答對了 ${combo}`:`答錯了，正確答案是 ${String.fromCharCode(65+state.current.answer)}`}</b>${renderExplanation(state.current)}`;elements.mainButton.textContent=state.lesson.active&&state.lesson.shouldEnd?"查看結果":"下一題";if(!(correct&&state.history.length%10===0))showReward(correct?`+${earnedXp} XP`:"愛心 -1",correct);updateStats();renderWorld()}
function startChallenge(){playSound("mission");state.wrongMode=false;state.questionBag=buildChallengeQueue();if(state.questionBag.length!==LESSON_SIZE)return alert("目前篩選後不足 10 個不同考點，請清除單元篩選後再開始挑戰。");state.lesson={active:true,answered:0,correct:0,xp:0,combo:0,hearts:hasRelic("木紋圓盾")?6:5,shouldEnd:false,seen:[],plannedIds:state.questionBag.map(item=>item.id)};document.body.classList.add("challenge-active","battle-active");elements.lessonProgress.classList.remove("hidden");showView("quiz");nextQuestion();updateStats()}
function exitChallenge(){if(state.lesson.answered&&!confirm("離開後本回合進度會結束，確定退出嗎？"))return;state.lesson.active=false;state.questionBag=[];document.body.classList.remove("challenge-active","battle-active");elements.lessonProgress.classList.add("hidden");nextQuestion();updateStats()}
function finishChallenge(){playSound("victory");const accuracy=state.lesson.answered?Math.round(state.lesson.correct/state.lesson.answered*100):0;elements.resultTitle.textContent=state.lesson.hearts===0?"別放棄，再來一關！":accuracy===100?"完美通關！":"挑戰完成！";elements.resultSummary.textContent=`已完成 ${state.lesson.answered} / ${LESSON_SIZE} 題，答對 ${state.lesson.correct} 題。`;elements.resultXp.textContent=`+${state.lesson.xp} XP`;elements.resultAccuracy.textContent=`${accuracy}%`;elements.resultModal.classList.remove("hidden");state.lesson.active=false;state.questionBag=[];document.body.classList.remove("challenge-active","battle-active");elements.lessonProgress.classList.add("hidden");save();updateStats();renderWorld()}
function closeResult(){elements.resultModal.classList.add("hidden");nextQuestion()}
function showView(view){playSound("nav");state.view=view;document.querySelectorAll("[data-view]").forEach(element=>element.classList.toggle("hidden",element.dataset.view!==view));document.querySelectorAll(".world-tab").forEach(button=>button.classList.toggle("active",button.dataset.viewTarget===view));if(view!=="quiz"&&state.lesson.active)exitChallenge();renderWorld()}
function hatchSeed(){if(state.world.seeds<1)return alert("再完成一些題目，就能得到新的種子！");const species=SPECIES.find(item=>item.subject===state.subject)||SPECIES[Math.floor(Math.random()*SPECIES.length)];state.world.seeds--;state.world.spirits[species.id]=(state.world.spirits[species.id]||0)+1;state.world.sunshine+=5;save();renderWorld();showReward(`${species.name}誕生了！`,true)}
function cultivateSeed(){const dewCost=hasRelic("幸運澆水壺")?5:10;if(state.world.sunshine<60||state.world.dew<dewCost)return alert(`培育種子需要 60 陽光與 ${dewCost} 露珠。`);state.world.sunshine-=60;state.world.dew-=dewCost;state.world.seeds++;save();renderWorld();showReward("培育出 1 顆神秘種子！",true)}
function buyBuilding(id){const building=BUILDINGS.find(item=>item.id===id);if(!building||hasBuilding(id))return;if(state.world.sunshine<building.cost)return alert(`建造 ${building.name} 需要 ${building.cost} 陽光。`);state.world.sunshine-=building.cost;state.world.buildings=[...(state.world.buildings||[]),id];save();renderWorld();showReward(`${building.name} 建造完成！`,true)}
function toggleTeam(id){const owned=state.world.spirits[id]||0,selected=state.world.team.filter(item=>item===id).length;if(!owned)return;if(selected<owned&&state.world.team.length<3)state.world.team.push(id);else if(selected>0)state.world.team.splice(state.world.team.lastIndexOf(id),1);else return alert("探索隊伍最多 3 隻芽靈");save();renderWorld()}
function equipRelic(relic){const target=state.world.team[0]||SPECIES.find(item=>(state.world.spirits[item.id]||0)>0)?.id;if(!target)return alert("請先培養一隻芽靈");state.world.equipment[target]=relic;save();renderWorld();showReward(`已裝備 ${relic}`,true)}
function startExpedition(type){if(state.world.expedition)return claimExpedition();if(state.world.team.length<3)return alert("請先到芽靈圖鑑選滿 3 隻探索隊員");let duration=type==="ruins"?300000:120000;if(hasRelic("葉片斗篷"))duration*=.85;if(hasRelic("風翼靴"))duration*=.75;state.world.expedition={type,endsAt:Date.now()+duration};save();renderWorld()}
function speedExpedition(){const trip=state.world.expedition;if(!trip||state.world.dew<10)return alert("加速探索需要 10 露珠。");state.world.dew-=10;trip.endsAt=Math.max(Date.now(),trip.endsAt-60000);save();renderWorld();showReward("探索時間縮短 1 分鐘",true)}
function claimExpedition(){const trip=state.world.expedition;if(!trip)return;if(Date.now()<trip.endsAt)return alert("探索隊伍還在路上！");const reward=trip.type==="ruins"?{sun:30,dew:12}:{sun:15,dew:7};let multiplier=hasBuilding("treehouse")?1.5:1;if(hasRelic("螢光提燈"))multiplier+=.2;if(hasRelic("古芽羅盤"))multiplier+=.25;state.world.sunshine+=Math.round(reward.sun*multiplier);state.world.dew+=Math.round(reward.dew*multiplier);const locked=RELICS.filter(item=>!state.world.relics.includes(item));if(locked.length)state.world.relics.push(locked[Math.floor(Math.random()*locked.length)]);state.world.expedition=null;save();renderWorld();showReward("帶回資源與隱藏寶物！",true)}
function renderWorld(){
  const miles=Math.floor(state.history.length*.4),total=Object.values(state.world.spirits).reduce((sum,count)=>sum+count,0);
  if(elements.exploreMiles)elements.exploreMiles.textContent=`${miles} km`;
  if(elements.missionTrack)elements.missionTrack.style.width=`${Math.min(100,(state.history.length%50)/50*100)}%`;
  elements.sunshineCount.textContent=state.world.sunshine;elements.dewCount.textContent=state.world.dew;elements.seedCount.textContent=state.world.seeds;elements.spiritTotal.textContent=`${total} 隻`;
  const dewCost=hasRelic("幸運澆水壺")?5:10;elements.cultivateSeed.textContent=`培育種子・60☀ ${dewCost}💧`;elements.cultivateSeed.disabled=state.world.sunshine<60||state.world.dew<dewCost;elements.hatchSeed.disabled=state.world.seeds<1;elements.hatchHint.textContent=state.world.seeds?`目前有 ${state.world.seeds} 顆種子；孵化種類依現在科目決定。`:`答題取得種子，或使用陽光與露珠主動培育。`;
  elements.gardenBuildings.innerHTML=BUILDINGS.map(item=>{const built=hasBuilding(item.id);return `<div class="building ${built?"unlocked":""}"><span>${built?item.icon:"🔒"}</span><b>${item.name}</b><small>${built?item.effect:`${item.cost} 陽光・${item.effect}`}</small>${built?"":`<button data-building="${item.id}" ${state.world.sunshine<item.cost?"disabled":""}>建造</button>`}</div>`}).join("");
  elements.gardenBuildings.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>buyBuilding(button.dataset.building)));
  elements.spiritGrid.innerHTML=SPECIES.map(item=>{const count=state.world.spirits[item.id]||0,selected=state.world.team.filter(id=>id===item.id).length,equipped=state.world.equipment[item.id];return `<article class="spirit-card ${item.color} ${count?"owned":"locked"}"><span class="spirit-icon">${item.icon}</span><div><h3>${item.name} <small>× ${count}</small></h3><p>${item.subject}系・${item.gift}${equipped?`<br>🎒 ${equipped}<span class="relic-effect">${RELIC_EFFECTS[equipped]}</span>`:""}</p></div><button data-spirit="${item.id}" ${count?"":"disabled"}>${selected&&selected>=count?`移除一隻 (${selected})`:`加入隊伍 (${selected})`}</button></article>`}).join("");
  elements.spiritGrid.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>toggleTeam(button.dataset.spirit)));
  elements.relicList.innerHTML=RELICS.map(item=>{const found=state.world.relics.includes(item);return `<button class="${found?"found":""}" data-relic="${item}" ${found?"":"disabled"}>${found?"✨":"？"} ${found?item:"未發現道具"}${found?`<span class="relic-effect">${RELIC_EFFECTS[item]}</span>`:""}</button>`}).join("");
  elements.relicList.querySelectorAll("button.found").forEach(button=>button.addEventListener("click",()=>equipRelic(button.dataset.relic)));
  elements.teamCount.textContent=`${state.world.team.length} / 3`;elements.teamSlots.innerHTML=Array.from({length:3},(_,index)=>{const id=state.world.team[index],item=SPECIES.find(species=>species.id===id);return `<div class="team-slot ${item?item.color:""}">${item?`<span>${item.icon}</span><b>${item.name}</b>`:`<span>＋</span><b>空位</b>`}</div>`}).join("");
  const trip=state.world.expedition;if(trip){const remaining=Math.max(0,Math.ceil((trip.endsAt-Date.now())/1000));elements.expeditionStatus.classList.remove("hidden");elements.expeditionStatus.innerHTML=remaining?`探索中…約 ${Math.ceil(remaining/60)} 分鐘後回來。<button class="game-action" id="speedTrip">10💧 加速 1 分鐘</button>`:`隊伍回來了！<button class="game-action" id="claimTrip">領取寶物</button>`;document.getElementById(remaining?"speedTrip":"claimTrip")?.addEventListener("click",remaining?speedExpedition:claimExpedition)}else elements.expeditionStatus.classList.add("hidden");
}
function updateStats(){const correct=state.history.filter(item=>item.correct??item.ok).length,today=todayHistory(),dailyGoal=Number(state.profile.dailyGoal)||DAILY_GOAL,progress=Math.min(today.length/dailyGoal*100,100);elements.doneCount.textContent=state.history.length;elements.accuracy.textContent=state.history.length?`${Math.round(correct/state.history.length*100)}%`:"—";elements.wrongCount.textContent=state.wrongs.length;elements.todayCount.textContent=today.length;elements.streakDays.textContent=streakDays();elements.xpCount.textContent=state.game.xp;elements.heartCount.textContent=state.lesson.active?state.lesson.hearts:5;elements.goalCount.textContent=Math.min(today.length,dailyGoal);const goalSmall=elements.goalRing.querySelector("small");if(goalSmall)goalSmall.textContent=`/ ${dailyGoal}`;elements.goalRing.style.setProperty("--goal",`${progress}%`);elements.questMessage.textContent=today.length>=dailyGoal?"今日目標達成！再玩一關探索更深處":`今天再答 ${dailyGoal-today.length} 題即可達標`;if(state.lesson.active){elements.progressBar.style.width=`${state.lesson.answered/LESSON_SIZE*100}%`;elements.lessonCount.textContent=`${state.lesson.answered} / ${LESSON_SIZE}`;elements.lessonHearts.textContent=`❤️ ${state.lesson.hearts}`}}
elements.mainButton.addEventListener("click",checkAnswer);elements.wrongButton.addEventListener("click",()=>{state.wrongMode=!state.wrongMode;state.questionBag=[];nextQuestion()});elements.difficultyFilter.addEventListener("change",event=>{state.difficulty=event.target.value;save();resetBagAndNext()});elements.unitFilter.addEventListener("change",event=>{state.unit=event.target.value;save();resetBagAndNext()});elements.resetFilters.addEventListener("click",()=>{state.difficulty="";state.unit="";elements.difficultyFilter.value="";elements.unitFilter.value="";save();resetBagAndNext()});elements.startChallenge.addEventListener("click",startChallenge);elements.exitChallenge.addEventListener("click",exitChallenge);elements.closeResult.addEventListener("click",closeResult);elements.cultivateSeed.addEventListener("click",cultivateSeed);elements.hatchSeed.addEventListener("click",hatchSeed);document.querySelectorAll(".world-tab").forEach(button=>button.addEventListener("click",()=>showView(button.dataset.viewTarget)));document.querySelectorAll(".expedition-button").forEach(button=>button.addEventListener("click",()=>startExpedition(button.dataset.expedition)));
migrateV1();elements.difficultyFilter.value=state.difficulty;renderTabs();loadSubject();updateStats();renderWorld();loadOfficialExams();setInterval(()=>{if(state.world.expedition)renderWorld()},30000);
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js?v=5.5.0"));

async function loadOfficialExams(){try{const response=await fetch("./data/official-exams.json?v=1");if(!response.ok)throw new Error(`HTTP ${response.status}`);const exams=await response.json();elements.officialExamList.innerHTML=exams.map(exam=>`<article class="official-year"><div><span>民國</span><b>${exam.year}</b><small>${exam.year+1911} 年</small></div><section>${Object.entries(exam.subjects).map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${name}</a>`).join("")}<a class="answer-link" href="${exam.answer}" target="_blank" rel="noopener noreferrer">✓ 參考答案</a><a class="description-link" href="${exam.description}" target="_blank" rel="noopener noreferrer">命題說明</a><a class="source-link" href="${exam.page}" target="_blank" rel="noopener noreferrer">官方來源</a></section></article>`).join("")}catch(error){elements.officialExamList.innerHTML=`<div class="empty">真題清單載入失敗：${error.message}</div>`}}
function profileSpirit(){return SPECIES.find(item=>item.id===state.profile.spirit)||SPECIES[3]}
function applyProfile(){const spirit=profileSpirit();document.body.dataset.theme=state.profile.theme;document.body.dataset.accent=state.profile.accent;document.body.classList.toggle("motion-off",!state.profile.motion);elements.explorerAvatar.textContent=state.profile.avatar||"遠";elements.heroSpirit.textContent=spirit.icon;elements.battleSpirit.textContent=spirit.icon;elements.soundToggle.textContent=state.profile.sound||state.profile.music?"🔊":"🔇";const shownName=state.profile.name?.trim();if(shownName)document.querySelector("#studentName").textContent=shownName}
function openProfile(){elements.profileName.value=state.profile.name||document.querySelector("#studentName").textContent||"";elements.profileAvatar.value=state.profile.avatar;elements.profileSpirit.value=state.profile.spirit;elements.profileTheme.value=state.profile.theme;elements.profileGoal.value=String(state.profile.dailyGoal);elements.profileAccent.value=state.profile.accent;elements.soundEnabled.checked=state.profile.sound;elements.motionEnabled.checked=state.profile.motion;elements.hapticEnabled.checked=state.profile.haptic;updateProfilePreview();elements.profileModal.classList.remove("hidden");playSound("nav")}
function updateProfilePreview(){const spirit=SPECIES.find(item=>item.id===elements.profileSpirit.value)||SPECIES[3];elements.profileAvatarPreview.textContent=elements.profileAvatar.value||"遠";elements.profileNamePreview.textContent=elements.profileName.value||"我的探索員";elements.profileSpiritPreview.textContent=spirit.icon}
function saveProfile(){state.profile={name:elements.profileName.value.trim(),avatar:(elements.profileAvatar.value.trim()||"遠").slice(0,1),spirit:elements.profileSpirit.value,theme:elements.profileTheme.value,accent:elements.profileAccent.value,dailyGoal:Number(elements.profileGoal.value)||20,sound:elements.soundEnabled.checked,music:state.profile.music,volume:state.profile.volume,motion:elements.motionEnabled.checked,haptic:elements.hapticEnabled.checked,configured:true};elements.profileModal.classList.add("hidden");applyProfile();save();updateStats();playSound("confirm")}
function ensureAudio(){if(!audioContext)audioContext=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==="suspended")audioContext.resume();return audioContext}
function tone(frequency,start,duration,type="sine",gain=.05){const context=ensureAudio(),oscillator=context.createOscillator(),volume=context.createGain();if(!effectsMaster){effectsMaster=context.createGain();effectsMaster.gain.value=state.profile.volume;effectsMaster.connect(context.destination)}oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,context.currentTime+start);volume.gain.setValueAtTime(.0001,context.currentTime+start);volume.gain.exponentialRampToValueAtTime(gain,context.currentTime+start+.012);volume.gain.exponentialRampToValueAtTime(.0001,context.currentTime+start+duration);oscillator.connect(volume).connect(effectsMaster);oscillator.start(context.currentTime+start);oscillator.stop(context.currentTime+start+duration+.02)}
function playSound(kind){if(!state.profile.sound)return;try{if(kind==="select")tone(330,0,.08,"triangle",.035);else if(kind==="nav")tone(240,0,.07,"sine",.025);else if(kind==="mission"){tone(220,0,.12,"triangle");tone(330,.09,.15,"triangle");tone(494,.18,.2,"triangle")}else if(kind==="correct"){tone(523,0,.12,"triangle",.07);tone(659,.08,.15,"triangle",.07);tone(784,.17,.28,"sine",.08)}else if(kind==="wrong"){tone(185,0,.16,"sine",.045);tone(147,.12,.22,"sine",.035)}else if(kind==="victory"){[392,523,659,784].forEach((note,index)=>tone(note,index*.09,.25,"triangle",.07))}else if(kind==="confirm"){tone(440,0,.1,"sine");tone(660,.08,.16,"triangle")}else if(kind==="reward"){tone(660,0,.12,"triangle");tone(880,.1,.26,"sine")}}catch{}}
function runBattleFeedback(correct,earnedXp){if(correct)burstParticles();const combo=state.lesson.active?state.lesson.combo:correct?1:0;elements.comboBadge.classList.toggle("hidden",combo<2);elements.comboBadge.querySelector("b").textContent=combo;elements.enemyShield.style.width=`${Math.max(0,100-(state.lesson.active?state.lesson.answered:1)*10)}%`;elements.battleStage.classList.remove("hit-correct","hit-wrong");void elements.battleStage.offsetWidth;elements.battleStage.classList.add(correct?"hit-correct":"hit-wrong");setTimeout(()=>elements.battleStage.classList.remove("hit-correct","hit-wrong"),950);playSound(correct?"correct":"wrong");if(state.profile.haptic&&navigator.vibrate)navigator.vibrate(correct?[25,35,45]:[55]);if(correct&&state.history.length%10===0)playSound("reward")}
function toggleSound(){const enabled=state.profile.sound||state.profile.music;state.profile.sound=!enabled;state.profile.music=!enabled;updateAudioControls();if(state.profile.music)startMusic();else stopMusic();save();if(state.profile.sound)playSound("confirm")}
document.querySelector("#openProfile").addEventListener("click",openProfile);document.querySelector("#closeProfile").addEventListener("click",()=>elements.profileModal.classList.add("hidden"));document.querySelector("#saveProfile").addEventListener("click",saveProfile);elements.soundToggle.addEventListener("click",toggleSound);[elements.profileName,elements.profileAvatar,elements.profileSpirit].forEach(input=>input.addEventListener("input",updateProfilePreview));elements.profileModal.addEventListener("click",event=>{if(event.target===elements.profileModal)elements.profileModal.classList.add("hidden")});
applyProfile();if(!state.profile.configured)setTimeout(openProfile,500);

function updateAudioControls(){elements.soundToggle.textContent=state.profile.sound||state.profile.music?"🔊":"🔇";elements.musicToggle.classList.toggle("off",!state.profile.music);elements.effectsToggle.classList.toggle("off",!state.profile.sound);elements.volumeControl.value=Math.round((state.profile.volume??.55)*100);elements.audioStatus.textContent=musicStarted&&state.profile.music?"Once Upon a Time・奇幻遠征配樂":"點一下頁面開啟音樂";if(bgmAudio){bgmAudio.volume=Math.min(1,(state.profile.volume??.55)*.55);bgmAudio.muted=!state.profile.music}if(effectsMaster)effectsMaster.gain.setTargetAtTime(state.profile.volume,audioContext.currentTime,.08)}
async function startMusic(){if(!state.profile.music)return;if(!bgmAudio){bgmAudio=new Audio("./assets/once-upon-a-time-loop.mp3");bgmAudio.loop=true;bgmAudio.preload="auto";bgmAudio.volume=Math.min(1,(state.profile.volume??.55)*.55)}bgmAudio.muted=false;try{await bgmAudio.play();musicStarted=true;updateAudioControls()}catch{elements.audioStatus.textContent="點一下頁面開啟音樂"}}
function stopMusic(){if(!bgmAudio)return;bgmAudio.pause();musicStarted=false;elements.audioStatus.textContent="音樂已暫停"}
function toggleMusic(){state.profile.music=!state.profile.music;if(state.profile.music)startMusic();else stopMusic();updateAudioControls();save();vibrate(10)}
function toggleEffects(){state.profile.sound=!state.profile.sound;updateAudioControls();save();if(state.profile.sound)playSound("confirm");vibrate(8)}
function setVolume(){state.profile.volume=Number(elements.volumeControl.value)/100;updateAudioControls();save()}
function vibrate(pattern){if(state.profile.haptic&&navigator.vibrate)navigator.vibrate(pattern)}
function burstParticles(){if(!state.profile.motion)return;for(let index=0;index<18;index++){const particle=document.createElement("i");particle.className="correct-burst";particle.style.left=`${65+Math.random()*20}%`;particle.style.top=`${12+Math.random()*24}%`;particle.style.setProperty("--dx",`${(Math.random()-.5)*260}px`);particle.style.setProperty("--dy",`${(Math.random()-.5)*220}px`);elements.impactLayer.append(particle);setTimeout(()=>particle.remove(),850)}}
function bindFullFeedback(){document.addEventListener("pointerdown",()=>{if(state.profile.music)startMusic()},{once:true});elements.musicToggle.addEventListener("click",toggleMusic);elements.effectsToggle.addEventListener("click",toggleEffects);elements.volumeControl.addEventListener("input",setVolume);document.querySelectorAll("button").forEach(button=>button.addEventListener("pointerenter",()=>{if(!button.disabled)playSound("nav")},{passive:true}));document.addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;if(button.matches(".world-tab,.tab,.game-action,.start-button"))vibrate(8)});updateAudioControls()}
bindFullFeedback();
