import { authenticatedFetch, getClerk } from "../vendor/auth-runtime.js";

let students=[];
let trend=[];
let subjects=[];
let metrics=[];
const colors={國文:"#ff765f",英文:"#5faad9",數學:"#ffbf3f",自然:"#62a66a",社會:"#8b78c9"};
const statusText={active:"今日活躍",attention:"需關注",inactive:"尚未開始"};
const config=window.CAP_QUIZ_ADMIN_CONFIG||{apiBase:"/api"};
const views={overview:{kicker:"平台營運總覽",title:"今天，每個孩子都走到哪裡了？"},students:{kicker:"學生狀態",title:"從每日小步驟看見每個人的節奏"},trends:{kicker:"學習趨勢",title:"題量之外，也看學習品質的變化"},attention:{kicker:"需要關注",title:"先理解卡關，再給合適的幫助"}};
const metricGrid=document.querySelector("#metricGrid"),studentRows=document.querySelector("#studentRows"),dialog=document.querySelector("#studentDialog"),detail=document.querySelector("#studentDetail"),banner=document.querySelector("#demoBanner");
const number=value=>Number(value||0).toLocaleString("zh-TW");
const percent=value=>`${Number(value||0).toFixed(1)}%`;
const relativeTime=value=>{if(!value)return"尚無紀錄";const minutes=Math.floor((Date.now()-new Date(value))/60000);if(minutes<1)return"剛剛";if(minutes<60)return`${minutes} 分鐘前`;const hours=Math.floor(minutes/60);if(hours<24)return`${hours} 小時前`;return`${Math.floor(hours/24)} 天前`};
const empty=message=>`<p style="color:#71806f;padding:18px 4px">${message}</p>`;
function renderMetrics(){metricGrid.innerHTML=metrics.length?metrics.map(x=>`<article class="metric" style="--accent:${x.c}"><small>${x.l}</small><strong>${x.v}</strong><em>${x.s}</em></article>`).join(""):empty("尚無可顯示的統計資料。")}
function renderTrend(){const chart=document.querySelector("#trendChart");if(!trend.length){chart.innerHTML=empty("近 7 日尚無作答紀錄。");return}const maxQuestions=Math.max(1,...trend.map(x=>x.questions));const maxUsers=Math.max(1,...trend.map(x=>x.active_users));chart.innerHTML=trend.map(x=>`<div class="day-column"><i class="bar users" style="height:${x.active_users/maxUsers*78}%" title="${x.active_users} 人"></i><i class="bar questions" style="height:${x.questions/maxQuestions*96}%" title="${x.questions} 題"></i><span class="day-label">${new Intl.DateTimeFormat("zh-TW",{weekday:"short"}).format(new Date(`${x.trend_day}T12:00:00`))}</span></div>`).join("");const previous=trend.at(-2)?.questions||0,current=trend.at(-1)?.questions||0;document.querySelector("#trendChange").textContent=previous?`${current>=previous?"↑":"↓"} ${Math.abs((current-previous)/previous*100).toFixed(1)}%`:`今日 ${current} 題`}
function renderSubjects(){const box=document.querySelector("#subjectBars");box.innerHTML=subjects.length?subjects.map(x=>`<div class="subject-row"><span>${x.subject}</span><div class="subject-track"><div class="subject-fill" style="width:${x.accuracy}%;background:${colors[x.subject]||"#71806f"}"></div></div><output>${percent(x.accuracy)}</output></div>`).join(""):empty("近 30 日尚無科目作答資料。")}
function renderAlerts(alerts={}){document.querySelector("#alertGrid").innerHTML=`<article class="alert-card red"><span class="alert-icon">◒</span><div><b>${number(alerts.inactive_3d)} 人連續 3 天未刷題</b><p>依最近一次真實作答時間統計。</p></div></article><article class="alert-card amber"><span class="alert-icon">△</span><div><b>${number(alerts.low_accuracy)} 人今日正確率低於 50%</b><p>僅計入今日至少作答 5 題者。</p></div></article><article class="alert-card blue"><span class="alert-icon">↻</span><div><b>${number(alerts.many_wrong)} 人近 30 日累積 10 題錯題</b><p>依真實錯題紀錄統計。</p></div></article>`}
function renderInsights(){const weakest=[...subjects].filter(x=>x.attempts>0).sort((a,b)=>a.accuracy-b.accuracy)[0];const total=trend.reduce((sum,x)=>sum+x.questions,0);document.querySelector("#insightGrid").innerHTML=`<article><span>01</span><h3>${weakest?`${weakest.subject}需要優先關注`:"尚無科目資料"}</h3><p>${weakest?`近 30 日正確率 ${percent(weakest.accuracy)}，共 ${number(weakest.attempts)} 次作答。`:"學生開始作答後才會產生分析。"}</p></article><article><span>02</span><h3>近 7 日完成 ${number(total)} 題</h3><p>數字直接來自 Neon 作答紀錄，不含本機未同步資料。</p></article><article><span>03</span><h3>資料更新規則</h3><p>重新整理即讀取最新 Clerk 帳號與 Neon 紀錄，不使用預設值。</p></article>`}
function renderRows(){const query=document.querySelector("#searchInput").value.trim().toLowerCase(),status=document.querySelector("#statusFilter").value;const filtered=students.filter(x=>(status==="all"||x.status===status)&&`${x.name}${x.id}`.toLowerCase().includes(query));studentRows.innerHTML=filtered.length?filtered.map(x=>`<tr data-id="${x.id}"><td><div class="student"><span class="avatar" style="background:#dce9aa">${x.avatar}</span><div><b>${x.name}</b><small>${x.id}</small></div></div></td><td><b>${number(x.today)} 題</b><div class="progress-mini"><i style="width:${Math.min(x.today/20*100,100)}%"></i></div></td><td>${percent(x.accuracy)}</td><td>🔥 ${x.streak} 天</td><td>${x.weak}</td><td>${x.last}</td><td><span class="status ${x.status}">● ${statusText[x.status]}</span></td></tr>`).join(""):`<tr><td colspan="7">${empty("沒有符合條件的真實學生資料。")}</td></tr>`;studentRows.querySelectorAll("tr[data-id]").forEach(row=>row.addEventListener("click",()=>openDetail(students.find(x=>x.id===row.dataset.id))))}
function openDetail(x){detail.innerHTML=`<div class="detail"><p class="kicker">${x.id}・學習檔案</p><h2>${x.name}的學習紀錄</h2><p class="detail-meta">此頁只顯示 Clerk 帳號與 Neon 作答紀錄。</p><div class="detail-grid"><div class="detail-stat"><strong>${x.today}</strong><span>今日完成題數</span></div><div class="detail-stat"><strong>${percent(x.accuracy)}</strong><span>近 30 日正確率</span></div><div class="detail-stat"><strong>${x.total}</strong><span>累計完成題數</span></div><div class="detail-stat"><strong>${x.streak}</strong><span>連續學習天數</span></div><div class="detail-stat"><strong>${x.wrong.length}</strong><span>近期弱點數</span></div></div><section class="detail-section"><h3>需要加強的知識點</h3><div class="weak-list">${x.wrong.length?x.wrong.map(w=>`<span>${w.name}（錯 ${w.count} 題）</span>`).join(""):"尚無足夠錯題資料"}</div></section></div>`;dialog.showModal()}
function showView(view){const selected=views[view]||views.overview;document.querySelectorAll("[data-panel]").forEach(panel=>panel.classList.toggle("hidden-panel",!panel.dataset.panel.split(" ").includes(view)));document.querySelectorAll(".nav-item[data-view]").forEach(button=>button.classList.toggle("active",button.dataset.view===view));document.querySelector("#pageKicker").textContent=selected.kicker;document.querySelector("#pageTitle").textContent=selected.title;history.replaceState(null,"",`#${view}`)}
async function loadLiveDashboard(){const response=await authenticatedFetch(`${config.apiBase||"/api"}/admin/dashboard`);if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.message||"無法載入管理資料。")}const data=await response.json(),summary=data.summary||{};metrics=[{l:"平台帳號",v:number(summary.student_count),s:"Clerk 已註冊使用者",c:"#e7f5d8"},{l:"今日活躍",v:number(summary.active_count),s:"今日至少完成 1 題",c:"#ddecf4"},{l:"今日完成題數",v:number(summary.answered_count),s:"臺北時間統計",c:"#fff0c9"},{l:"今日平均正確率",v:percent(summary.accuracy),s:"Neon 真實作答紀錄",c:"#ffe2da"}];students=(data.students||[]).map(item=>{const name=item.display_name||"學習者",accuracy=item.accuracy_base?item.correct_count/item.accuracy_base*100:0,last=item.last_activity_at,status=item.answered_count>0?"active":last&&Date.now()-new Date(last)<3*864e5?"attention":"inactive";return{id:item.public_code,name,avatar:name.slice(0,1),today:item.answered_count||0,accuracy,streak:item.streak||0,weak:item.weakest_points?.[0]?.name||"尚無明顯弱點",last:relativeTime(last),status,total:item.total_count||0,wrong:item.weakest_points||[]}});trend=data.trend||[];subjects=data.subjects||[];renderMetrics();renderTrend();renderSubjects();renderAlerts(data.alerts);renderInsights();renderRows();banner.innerHTML=`<b>真實資料</b> Clerk 帳號與 Neon 作答紀錄已同步；更新於 ${new Date(data.generatedAt).toLocaleString("zh-TW")}`;document.querySelector("#reportDate").textContent=new Intl.DateTimeFormat("zh-TW",{dateStyle:"full"}).format(new Date())+"・即時讀取"}
document.querySelector("#searchInput").addEventListener("input",renderRows);document.querySelector("#statusFilter").addEventListener("change",renderRows);document.querySelector("#closeDialog").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});document.querySelectorAll(".nav-item[data-view]").forEach(button=>button.addEventListener("click",()=>showView(button.dataset.view)));document.querySelector("#showAllAlerts").addEventListener("click",()=>showView("attention"));
showView(location.hash.slice(1)||"overview");
const clerk=await getClerk();if(!clerk.user)location.replace("./login.html");else loadLiveDashboard().catch(error=>{students=[];trend=[];subjects=[];metrics=[];renderMetrics();renderTrend();renderSubjects();renderRows();document.querySelector("#alertGrid").innerHTML=empty("真實警示資料載入失敗。");document.querySelector("#insightGrid").innerHTML=empty("真實趨勢資料載入失敗。");banner.innerHTML=`<b>真實資料載入失敗</b> ${error.message}（未顯示任何示範資料）`});
